### ISSUE TITLE
Unable to recognize config values for SSL enabled cluster

### ISSUE THREAD

**Issue by prashanth-hegde** [adevinta/zoe#16]
Unable to parse configuration while reading from a cloud server 

**Error message:** 
```bash
$ zoe --env stage --cluster inventory topics consume transactions
2020-09-18 09:39:26 INFO zoe: loading config from url : file:/Users/Z002DCM/.zoe/config/stage.yml
error: Parameter specified as non-null is null: method com.adevinta.oss.zoe.service.secrets.ExtensionsKt.
secretOrRaw, parameter value
```

**Configuration:**
```yml
---
runners:
  default: "local"
storage: null
secrets: null
expressions: {}
clusters:
  inventory:
    registry: null
    topics:
      transactions:
        name: "inventory-transactions"
        subject: "Inventory Transactions"
        propsOverride: {}
    props:
      bootstrap.servers: "kafka-ttc-cloud.com:9093"
      key.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value.serializer: "org.apache.kafka.common.serialization.StringDeserializer"
      security.protocol: "SSL"
      ssl.truststore.location: "/absolute/path/to/client.jks"
      ssl.truststore.password: "my_password"
      ssl.keystore.location: "/absolute/path/to/server.jks"
      ssl.keystore.password: "my_password"
      ssl.endpoint.identification.algorithm:
    groups: {}
```
