### ISSUE TITLE
Topic operations without privileges

### ISSUE THREAD

**Issue by dariocazas** [adevinta/zoe#20]
Some basic operations available in zoe 0.24.0 gets an auth error in versions 0.25.0 and 0.26.0, like:
- List topics
- Describe topics

Using the following scripts:

```sh
# Test zoe 0.24.0
sudo rpm -e zoe
ZOE_VERSION=0.24.0
sudo rpm -i "https://github.com/adevinta/zoe/releases/download/v${ZOE_VERSION}/zoe-${ZOE_VERSION}-1.x86_64.rpm"
zoe topics list

# Test zoe 0.25.0
sudo rpm -e zoe
ZOE_VERSION=0.25.0
sudo rpm -i "https://github.com/adevinta/zoe/releases/download/v${ZOE_VERSION}/zoe-${ZOE_VERSION}-1.x86_64.rpm"
zoe topics list

# Test zoe 0.26.0
sudo rpm -e zoe
ZOE_VERSION=0.26.0
sudo rpm -i "https://github.com/adevinta/zoe/releases/download/v${ZOE_VERSION}/zoe-${ZOE_VERSION}-1.x86_64.rpm"
zoe topics list
```

With those results:
- CASE: use an user (configured in `sasl.jaas.config`) with only privileges about READ and DESCRIBE on several topics:
    - 0.24.0: gets the topics that the configured user has privileges
    - 0.25.0: gets error
    - 0.26.0: gets error
- CASE: use kafka admin user:
    - 0.24.0: gets all non internal topics
    - 0.25.0: gets all non internal topics
    - 0.26.0: gets all non internal topics

The error showed is:
```yml
failure: runner 'local' failed
cause:
  failure: org.apache.kafka.common.errors.TopicAuthorizationException: Topic authorization failed.
  cause:
      failure: Topic authorization failed.
```

About config against kafka server:
```yml
      client.id: "zoe-client"
      sasl.mechanism: "SCRAM-SHA-512"
      sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"user1\" password=\"user1pass\";"
      security.protocol: "SASL_SSL"
      ssl.truststore.location: "/home/myuser/.zoe/config/kafka_keystore.jks"
      ssl.truststore.password: "changeit"
      ssl.endpoint.identification.algorithm: "https"
```
